// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModernRecrut.Postulations.API.Data;

#nullable disable

namespace ModernRecrut.Postulations.API.Migrations
{
    [DbContext(typeof(ModernRecrutPostulationContext))]
    partial class ModernRecrutPostulationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.18");

            modelBuilder.Entity("ModernRecrut.Postulations.API.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NoteEmeteur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NoteRh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PostulationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PostulationId");

                    b.ToTable("Note");
                });

            modelBuilder.Entity("ModernRecrut.Postulations.API.Models.Postulation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateDisponibilite")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdCandidat")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OffreDemploiID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PretentionSalariale")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Postulation");
                });

            modelBuilder.Entity("ModernRecrut.Postulations.API.Models.Note", b =>
                {
                    b.HasOne("ModernRecrut.Postulations.API.Models.Postulation", "Postulation")
                        .WithMany("Notes")
                        .HasForeignKey("PostulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Postulation");
                });

            modelBuilder.Entity("ModernRecrut.Postulations.API.Models.Postulation", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
