parameters:
  buildConfiguration: 'Release'
  artifactName: ''

jobs:
 - job: BuildLinux
   pool:
     vmImage: 'ubuntu-latest'

   steps:
   - task: DotNetCoreCLI@2
     inputs:
       command: 'restore'
       projects: '**/*.csproj'
       feedsToUse: 'select'
     displayName: 'Restauration des packages'

   - task: DotNetCoreCLI@2
     inputs:
       command: 'build'
       projects: '**/*.csproj'
       arguments: '--configuration  ${{ parameters.buildConfiguration }}'
     displayName: 'Génération de la solution'

   - task: DotNetCoreCLI@2
     inputs:
       command: 'test'
       projects: '**/*Tests.csproj'
       arguments: '--configuration ${{ parameters.buildConfiguration }}'
     displayName: 'Exécution des tests unitaires'

   - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '**/*MVC.csproj'
        arguments: '--configuration ${{ parameters.buildConfiguration }} --output $(Build.ArtifactStagingDirectory)'
      displayName: 'Génération du package de publication MVC'

   - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '**/*Tests.csproj'
        arguments: '--configuration ${{ parameters.buildConfiguration }} --output $(Build.ArtifactStagingDirectory)'
      displayName: 'Génération du package de publication Tests'

   - task: PublishBuildArtifacts@1
     inputs:
       PathtoPublish: '$(Build.ArtifactStagingDirectory)'
       ArtifactName: '${{ parameters.artifactName }}'
       publishLocation: 'Container'
     displayName: 'Publication du package dans Azure DevOps'