parameters:
    environment: ''
    artifactName: ''
    serviceConnection: ''
    apiAppName: ''

jobs:
- deployment : '${{ parameters.apiAppName }}'
  pool: 
    vmImage: 'ubuntu-latest'
  environment: '${{ parameters.environment }}'
  strategy:
        runOnce:
         deploy:
           steps:
           - task: DownloadBuildArtifacts@0
             inputs:
               buildType: 'current'
               downloadType: 'single'
               artifactName: '${{ parameters.artifactName } { apiAppName }}'
               downloadPath: '$(System.ArtifactsDirectory)'
              #displayName: 'Téléchargement du package'

           - task: AzureRmWebAppDeployment@4
             inputs:
               ConnectionType: 'AzureRM'
               azureSubscription: '${{ parameters.serviceConnection }}'
               appType: 'webApp'
               WebAppName: '${{ parameters.apiAppName }}'
               package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
             displayName: 'Déploiement de l'API'