parameters:
    environment: ''
    artifactName: ''
    serviceConnection: ''
    apiAppName: ''

jobs:
- deployment : 'WebDeploy'
  pool: 
    vmImage: 'ubuntu-latest'
  environment: '${{ parameters.environment }}'
  strategy:
        runOnce:
         deploy:
           steps:
           - task: DownloadBuildArtifacts@0
             inputs:
               buildType: 'current'
               downloadType: 'single'
               artifactName: '${{ parameters.artifactName }}'
               downloadPath: '$(System.ArtifactsDirectory)'

           - task: AzureRmWebAppDeployment@4
             inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: '${{ parameters.serviceConnection }}'
              appType: 'apiApp'
              ApiAppName: '${{ parameters.apiAppName }}'
              package: '$(Build.ArtifactStagingDirectory)/**/*.zip'