parameters:
    environment: ''
    artifactName: ''
    serviceConnection: ''
    apiAppName: ''
    nomComplet: ''

jobs:
- deployment : '${{ parameters.apiAppName }}'
  pool: 
    vmImage: 'ubuntu-latest'
  environment: '${{ parameters.environment }}'
  strategy:
        runOnce:
         deploy:
           steps:
           - task: DownloadBuildArtifacts@0
             inputs:
               buildType: 'current'
               downloadType: 'single'
               artifactName: '${{ parameters.artifactName }}'
               downloadPath: '$(System.ArtifactsDirectory)'
              #displayName: 'Téléchargement du package' Bonne idée mais empêche le tout de fonctionner

           - task: AzureRmWebAppDeployment@4
             inputs:
               ConnectionType: 'AzureRM'
               azureSubscription: '${{ parameters.serviceConnection }}'
               appType: 'webApp'
               WebAppName: '${{ parameters.apiAppName }}'
               package: '$(Build.ArtifactStagingDirectory)/**/${{ parameters.nomComplet }}.zip'
             #displayName: 'Déploiement de l'API' Bonne idée mais empêche le tout de fonctionner