parameters:
    environment: ''
    artifactName: ''
    serviceConnection: ''
    apiAppName: ''


jobs:
- pool: 
    vmImage: 'ubuntu-latest'
- deployment : '${{ parameters.apiAppName }}'
  environment: '${{ parameters.environment }}'
  strategy:
        runOnce:
         deploy:
           steps:
           - task: DownloadBuildArtifacts@0
             inputs:
               buildType: 'current'
               downloadType: 'single'
               artifactName: '${{ parameters.artifactName }}'
               downloadPath: '$(System.ArtifactsDirectory)'
              displayName: 'Téléchargement du package'

           - task: AzureWebApp@1
              inputs:
                azureSubscription: '${{ parameters.serviceConnection }}'
                appType: 'apiApp'
                appName: '${{ parameters.apiAppName }}'
                package: '$(System.ArtifactsDirectory)/**/*.zip'
                deploymentMethod: 'auto's
              displayName: 'Déploiement de application'