# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - bicep

variables:
   artifactName: 'drop'
   serviceConnection: 'sc-tp3-devops'


stages:
- stage: 'Build'
  displayName: 'Génération, exécution des tests et publication'
  jobs:
  - template: Templates/Build-Template.yml
    parameters:
      buildConfiguration: 'Release'
      artifactName: '$(artifactName)'
  
- stage: 'DeployApiToDev'
  displayName: 'Déploiement des API en Dev'
  dependsOn: 'Build'
  jobs:
  - template: Templates/DeployAPI-Template.yml
    parameters:
      environment: 'Dev'
      artifactName: '$(artifactName)'
      serviceConnection: '$(serviceConnection)'
      apiAppName: 'webapp_documents_jlkc5cyuxxeum'

  - template: Templates/DeployAPI-Template.yml
    parameters:
      environment: 'Dev'
      artifactName: '$(artifactName)'
      serviceConnection: '$(serviceConnection)'
      apiAppName: 'webapp_emplois_jlkc5cyuxxeum'

  - template: Templates/DeployAPI-Template.yml
    parameters:
      environment: 'Dev'
      artifactName: '$(artifactName)'
      serviceConnection: '$(serviceConnection)'
      apiAppName: 'webapp_favoris_jlkc5cyuxxeum'

  - template: Templates/DeployAPI-Template.yml
    parameters:
      environment: 'Dev'
      artifactName: '$(artifactName)'
      serviceConnection: '$(serviceConnection)'
      apiAppName: 'webapp_postulation_jlkc5cyuxxeum'

- stage: 'DeployMvcToDev'
  displayName: 'Déploiement du MVC en Dev'
  dependsOn: 'DeployApiToDev'
  jobs:
  - template: Templates/DeployMVC-Template.yml
    parameters:
      environment: 'Dev'
      artifactName: '$(artifactName)'
      serviceConnection: '$(serviceConnection)'
      webAppName: 'webapp_mvc_jlkc5cyuxxeum'

- stage: 'DeployApiToProd'
  displayName: 'Déploiement des API en Prod'
  dependsOn: 'DeployMvcToDev'
  jobs:
  - template: Templates/DeployAPI-Template.yml
    parameters:
      environment: 'Prod'
      artifactName: '$(artifactName)'
      serviceConnection: '$(serviceConnection)'
      apiAppName: 'webapp_documents_jlkc5cyuxxeum'

  - template: Templates/DeployAPI-Template.yml
    parameters:
      environment: 'Prod'
      artifactName: '$(artifactName)'
      serviceConnection: '$(serviceConnection)'
      apiAppName: 'webapp_emplois_jlkc5cyuxxeum'

  - template: Templates/DeployAPI-Template.yml
    parameters:
      environment: 'Prod'
      artifactName: '$(artifactName)'
      serviceConnection: '$(serviceConnection)'
      apiAppName: 'webapp_favoris_jlkc5cyuxxeum'

  - template: Templates/DeployAPI-Template.yml
    parameters:
      environment: 'Prod'
      artifactName: '$(artifactName)'
      serviceConnection: '$(serviceConnection)'
      apiAppName: 'webapp_postulation_jlkc5cyuxxeum'

- stage: 'DeployMvcToProd'
  displayName: 'Déploiement du MVC en Prod'
  dependsOn: 'DeployApiToProd'
  jobs:
  - template: Templates/DeployMVC-Template.yml
    parameters:
      environment: 'Prod'
      artifactName: '$(artifactName)'
      serviceConnection: '$(serviceConnection)'
      webAppName: 'webapp_mvc_jlkc5cyuxxeum'

  - job: waitForValidation
    displayName: Wait for external validation  
    pool: server    
    timeoutInMinutes: 4320 # job times out in 3 days
    steps:   
    - task: ManualValidation@0
      timeoutInMinutes: 1440 # task times out in 1 day
      inputs:
          notifyUsers: |
              2145612@cegeplimoilou.ca
          instructions: 'Please validate the build configuration and resume'
          onTimeout: 'resume'